# Generated by Django 3.2.7 on 2021-09-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code_url',
            field=models.CharField(default='https://firebasestorage.googleapis.com/v0/b/kode-36169.appspot.com/o/productCodeFiles%2F256b5ee0-afbe-441d-bdcb-2b4e7efc47af.zip?alt=media&token=58e7473f-1e8a-46d6-b74a-a3d374f33410', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='https://dummyimage.com/450x300/dee2e6/6c757d.jpg', max_length=500),
        ),
    ]
