# Generated by Django 3.2.7 on 2021-09-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='order_id',
        ),
    ]
