# Generated by Django 3.2.7 on 2021-09-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_transaction_id_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(default='', max_length=200),
        ),
    ]
