# Generated by Django 3.2.7 on 2021-09-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
