# Generated by Django 3.2.7 on 2021-09-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='https://dummyimage.com/450x300/dee2e6/6c757d.jpg', max_length=500),
        ),
    ]
