# Generated by Django 3.2.7 on 2021-09-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageurl',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
