# Generated by Django 3.2.7 on 2021-09-27 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_imageurl_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
