# Generated by Django 3.2.7 on 2021-09-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Others', 'Others'), ('C++', 'C++')], default='others', max_length=100),
        ),
    ]
