# Generated by Django 3.2.7 on 2021-11-24 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210930_0115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
